Added SKLearn-like random forest API.
rapidsai/dask-xgboost pull request #1
Opened 2019-03-14 21:21 UTC by canonizer

2019-03-14 23:10 UTC, mtjrider requested changes

2019-03-14 23:10 UTC, mtjrider commented on dask_xgboost/core.py
> +def _xgb_regressor_fit(obj, X, y):
Methods should be fully encapsulated within a class object unless they are utilities useful for core operation.

2019-03-14 23:10 UTC, mtjrider commented on dask_xgboost/core.py
>  class XGBRegressor(xgb.XGBRegressor):
I think it makes the most sense to have a single class object called `XGBRegressor` which initializes, in a self-consistent way, both the code path for RF regression, and standard boosted regression.

2019-03-14 23:10 UTC, mt-jones commented on dask_xgboost/core.py
> +class XGBRFRegressor(xgb.XGBRFRegressor):
To unify the two class objects defined here, I think we have a few options:
```
class XGBRegressor(xgb.XGBRegressor, xgb.XGBRFRegressor):
  def __init__(self):
    self.RF = False # boolean flag to determine which regressor to use in Python
  def fit(self, ...):
    if(self.RF): ...
    ...
  def predict(self, ...):
    if(self.RF): ...
    ...

class XGBClassifier(xgb.XGBClassifier, xgb.XGBRFClassifier):
...
```

or something like:
```
class XGBRegressor:
  def __init__(self):
    self.XGBReg = xgb.XGBRegressor()
    self.XGBRFReg = xgb.XGBRFRegressor()
...
```

2019-03-14 23:10 UTC, mt-jones commented on dask_xgboost/core.py
> +def _xgb_regressor_predict(obj, X):
In `master`, `def _*` methods are reserved for Dask utilities, and parent calls which we don't intend to expose to the user.

Method useful for a particular class object are encapsulated by that class, and generally not hidden.

2019-03-14 23:53 UTC, canonizer commented
I've updated the classes; they now use mixins and multiple inheritance.

2019-03-15 00:24 UTC, mtjrider approved these changes

2019-03-15 00:41 UTC, merged